# Your name and what you do
name: Brandon Carlson
bio: Software Developer / Data Scientist

description: Brandon Carlson's Personal Website

# Profile picture
picture: assets/images/profile.jpg

# your url: http://USERNAME.github.io
url: https://blcarlson01.github.io/

# do you want to display social media links? true or false
social-media: true
# Add your username for the social media websites listed below
# If you don't have an account on any of them, comment out the line
# facebook: myfacebook
twitter: maverock01
linkedin: brandon-lee-carlson
github: blcarlson01
email: blcarlson@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
# youtube: myyoutube
# spotify: myspotify
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want to display an about section? true or false
about: false

# do you want to display a skills section? true or false
skills: false

# add your skills here
skills-list:
    - Javascript, NodeJS
    - AngularJS
    - Java
    - C#
    - Python
    - MySQL - MongoDB - Oracle - SQL Server  
    - Git
    - Scrum
    - Computer Security
    - Machine Learning - Natural Language Processing
    - XML
    - JSON
    - MVVM
    - ElasticSearch
    
# do you want to display a projects section? true or false
projects: true

# add your projects here
project-list:
    OSS:
        name: B. Carlson, K. Leach, D. Marinov, M. Nagappan, and A. Prakash
        conference: Open Source Vulnerability Notification
        conference-description: 15th International Conference on Open Source Systems
        location: (OSS 2019), pg 12-23, Montreal, Canada, May 2019 (Industry report.)
        url: https://link.springer.com/chapter/10.1007/978-3-030-20883-7_2
        preprint: assets/papers/CarlsonETAL19VulnerabilityNotification.pdf
        presentationTitle: OSS 2019 Presentation Slides
        presentation: assets/presentations/OSS2019-OpenSourceVulnerabilityNotification.pdf
        ieee-spectrum: https://spectrum.ieee.org/tech-talk/computing/software/github-releases-new-tools-to-report-vulnerabilities

# do you want to display the theme attribution? true or false
footer: true

# Enable animations? true or false
animation: true

gems:
  - jekyll-seo-tag

exclude: [README.md, Gemfile, Gemfile.lock, _site, Rakefile, travis.sh, vendor]
